#!/bin/bash

post_install() {
    cat <<END >~/.gtkrc-2.0
gtk-theme-name="adw-gtk3-dark"
gtk-icon-theme-name="Papirus-Dark"
END
}

install_yay() {
    (
        cd /tmp
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si
    )
}

pacman_dependencies=(
    # fonts
    noto-fonts
    noto-fonts-cjk

    # base
    hyprland
    hyprpaper
    wl-clipboard
    fish
    dunst
    copyq
    rofi
    kitty
    fcitx5
    fcitx5-bamboo
    fcitx5-configtool
    libnotify
    lsof
    gnome-keyring
    nvidia-open
    nvidia-settings
    power-profiles-daemon
    qt5ct
    qt6ct
    qt5-wayland
    qt6-wayland
    adw-gtk-theme
    papirus-icon-theme
    xdg-desktop-portal
    xdg-desktop-portal-gtk
    xdg-desktop-portal-hyprland

    # volume
    rtkit
    pipewire
    pipewire-jack
    wireplumber
    pipewire-alsa
    pipewire-pulse

    # tools
    bluez
    bluez-utils
    brightnessctl
    upower
    gammastep
    grim
    slurp
    htop
    jq
    unzip
    p7zip
    fastfetch
    lf
    fd
    ripgrep
    lazygit
    ffmpeg
    imagemagick
    inotify-tools
)

yay_dependencies=(
    # fonts
    ttf-joypixels

    # base
    brave-bin
    quickshell-git
    adwaita-dark

    # volume
    pwvucontrol

    # tools
    asusctl
    rog-control-center
)

usage() {
    cat <<END
usage: $0 <opt>
<opt>: -a: copy all files
       -c: link .config/files
       -f: copy fonts
       -i: install dependent packages
END
    exit 1
}

while getopts :abncfi opt; do
    case $opt in
    a) a=1 ;;
    c) c=1 ;;
    f) f=1 ;;
    i) i=1 ;;
    *) usage ;;
    esac
done

if [[ -z $1 ]]; then usage; fi

if [[ -n $a ]] || [[ -n $c ]]; then
    rm -fr ~/.xinitrc
    xinit="$(pwd)/.xinitrc"
    (
        set -x
        ln -sf "$xinit" ~
    )

    mkdir -p ~/.config
    for cfg in $(ls .config); do
        config="$(pwd)/.config/$cfg"
        eval "rm -fr ~/.config/$cfg"
        (
            set -x
            ln -sf "$config" ~/.config
        )
    done
fi

if [[ -n $a ]] || [[ -n $f ]]; then
    mkdir -p ~/.local/share/fonts
    tar xvf ./fonts/SourceCodePro.tar.xz -C ~/.local/share/fonts
fi

if [[ -n $a ]] || [[ -n $i ]]; then
    sudo pacman -S --noconfirm "${pacman_dependencies[@]}"
    if ! command -v yay; then install_yay; fi
    yay -S --noconfirm "${yay_dependencies[@]}"
    post_install
fi

# vi: sw=4 ts=4
