general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/hypr/imgs/hyprgirl.jpeg
    blur_passes = 2
    blur_size = 6
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = rgba(ffffffee)
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 18
    color = rgba(ffffffcc)
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    inner_color = rgba(1a1a1aee)
    font_color = rgba(ffffffee)
    placeholder_text = <i>Password...</i>
    fade_on_empty = true
    position = 0, -40
    halign = center
    valign = center
}
