# see all configures in `man 5 alacritty`

[general]
import = ["~/.config/alacritty/tokyonight_moon.toml"]

[cursor]
unfocused_hollow = false
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 12

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[window]
option_as_alt = "OnlyLeft"

[window.dimensions]
lines = 40
columns = 120

[keyboard]
bindings = [
  { mods = "Shift|Control", key = "T", action = "SpawnNewInstance" },
  { mods = "Alt", key = "H", action = "SelectPreviousTab" },
  { mods = "Alt", key = "L", action = "SelectNextTab" },
]
